### ISSUE TITLE
Source for low-load

### ISSUE THREAD

**Issue by eeucalyptus** [mclewell/buildroot-Ox64#1]
This is totally awesome. I started working on a buildroot-port for the Ox64 but I guess this Repo is already so far ahead of what I did, haha. 

What I'm missing is the sources (or just the patches) for the low-load firmware. Could you provide your changes, especially the changes in the UART3 pin assignment? I'd love to see your solution and build the FW myself. 

Thank you for your effort and good job so far!

**Comment by mclewell** [comment]
Take a look at the `0001-Use-UART3-as-console-output.patch` in the `patches` directory. The low-load firmware is build out of the BL808_SDK source ([specifically this cmake example](https://github.com/bouffalolab/bl808_linux/tree/main/bl_mcu_sdk_bl808/examples/low_load)). The patch modifies the pinmux header to enable UART3 on pins 16/17. It also modifies OpenSBI to use UART3 as the output console. "My patch" is actually directly taken from the BL808 source, which has the [same mod but for a similar board.](https://github.com/bouffalolab/bl808_linux/blob/main/patch/m1sdock/m1sdock_uart_pin_def.patch)

If you want to build the low-load firmware yourself, run the `./build.sh low-load` script as detailed on the [bl808_linux repo](https://github.com/bouffalolab/bl808_linux)

**Comment by eeucalyptus** [comment]
Oh! I see, sorry that was my mistake. I seem to have missed the patch. Thank you for your reply!
